-- DCM Project: RBAC Grants for Coles Retail Semantic View
-- Grants access to ANALYST_ROLE for querying the semantic view

GRANT USAGE ON DATABASE COLES_RETAIL_DB{{env_suffix}} TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA COLES_RETAIL_DB{{env_suffix}}.AI_ANALYTICS TO ROLE ANALYST_ROLE;

-- SELECT for querying, REFERENCES for use with Cortex Agents
GRANT SELECT, REFERENCES ON SEMANTIC VIEW
  COLES_RETAIL_DB{{env_suffix}}.AI_ANALYTICS.COLES_RETAIL_SEMANTIC_MODEL
  TO ROLE ANALYST_ROLE;

-- Grant access to underlying tables (required for Cortex Agents)
GRANT SELECT ON ALL TABLES IN SCHEMA COLES_RETAIL_DB{{env_suffix}}.AI_ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA COLES_RETAIL_DB{{env_suffix}}.AI_ANALYTICS TO ROLE ANALYST_ROLE;
