-- VIEW: AI_ANALYTICS.V_STORES

DEFINE view COLES_RETAIL_DB{{env_suffix}}.AI_ANALYTICS.V_STORES(
  LOC_ID,
  LOC_CDE,
  LOC_NM,
  FMT_CDE,
  RGN_CDE,
  ST_CDE,
  CITY_NM,
  POSTCODE,
  STORE_SIZE_SQM,
  EMPLOYEE_COUNT,
  OPENING_DATE,
  IS_ACTIVE,
  FMT_GRP
) as
SELECT 
    s.LOC_ID,
    s.LOC_CDE,
    n.LOC_NM,
    s.FMT_CDE,
    s.RGN_CDE,
    s.ST_CDE,
    s.CITY_NM,
    s.POSTCODE,
    s.STORE_SIZE_SQM,
    s.EMPLOYEE_COUNT,
    s.OPENING_DATE,
    s.IS_ACTIVE,
    s.FMT_GRP
FROM COLES_RETAIL_DB{{env_suffix}}.CORE.DIM_STORES s
JOIN COLES_RETAIL_DB{{env_suffix}}.AI_ANALYTICS.DIM_STORE_NAMES n ON s.LOC_ID = n.LOC_ID;
