-- Deploy: Suppliers dimension table
-- Executed via: EXECUTE IMMEDIATE FROM @AUTOMATIONS_REPO/branches/main/semantic-view/02-git-repository/deploy/tables/dim_suppliers.sql

CREATE TABLE IF NOT EXISTS COLES_RETAIL_DB.SUPPLY_CHAIN.DIM_SUPPLIERS (
  SUPPLIER_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  SUPPLIER_CODE VARCHAR(20),
  SUPPLIER_NAME VARCHAR(200),
  COUNTRY VARCHAR(50),
  CATEGORY VARCHAR(50),
  CONTACT_EMAIL VARCHAR(200),
  LEAD_TIME_DAYS NUMBER(38,0),
  RELIABILITY_SCORE NUMBER(3,2),
  IS_CERTIFIED_ORGANIC BOOLEAN,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (SUPPLIER_ID)
);
