-- Deploy: Product Master view
-- Executed via: EXECUTE IMMEDIATE FROM @AUTOMATIONS_REPO/branches/main/semantic-view/02-git-repository/deploy/views/v_product_master.sql

CREATE OR REPLACE VIEW COLES_RETAIL_DB.AI_ANALYTICS.V_PRODUCT_MASTER (
  MERCH_ID, ITEM_CDE, ITEM_DESC, CATEGORY_CODE, PRODUCT_CATEGORY,
  SUBCATEGORY, BRAND, PRIVATE_LABEL, STD_PRC, COST_PRC
) AS
SELECT
  MERCH_ID, ITEM_CDE, ITEM_DESC,
  DIV_CDE AS CATEGORY_CODE,
  CASE DIV_CDE
    WHEN 'D01' THEN 'Bakery'
    WHEN 'D02' THEN 'Beverages'
    WHEN 'D03' THEN 'Cereals'
    WHEN 'D04' THEN 'Dairy'
    WHEN 'D05' THEN 'Frozen'
    WHEN 'D06' THEN 'Household'
    WHEN 'D07' THEN 'Meat'
    WHEN 'D08' THEN 'Pantry'
    WHEN 'D09' THEN 'Produce'
  END AS PRODUCT_CATEGORY,
  SUBGRP_CDE AS SUBCATEGORY,
  SUPPLIER_KEY AS BRAND,
  PVT_FLG AS PRIVATE_LABEL,
  STD_PRC,
  COST_PRC
FROM COLES_RETAIL_DB.CORE.DIM_PRODUCTS;
