-- TABLE: MARKETING.FACT_SUPPORT_TICKETS

CREATE TABLE IF NOT EXISTS FACT_SUPPORT_TICKETS (
  TICKET_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
  CREATED_DATE TIMESTAMP_NTZ(9),
  STORE_ID NUMBER(38,0),
  CUSTOMER_ID NUMBER(38,0),
  CHANNEL VARCHAR(20),
  PRIORITY VARCHAR(20),
  SUBJECT VARCHAR(200),
  DESCRIPTION VARCHAR(2000),
  STATUS VARCHAR(20),
  AI_CATEGORY VARCHAR(50),
  PRODUCT_CATEGORY VARCHAR(50),
  primary key (TICKET_ID)
);
