-- TABLE: MARKETING.FACT_CUSTOMER_REVIEWS

CREATE TABLE IF NOT EXISTS FACT_CUSTOMER_REVIEWS (
  REVIEW_ID NUMBER(38,0),
  REVIEW_DATE DATE,
  STORE_ID NUMBER(38,0),
  CUSTOMER_ID NUMBER(38,0),
  PRODUCT_ID NUMBER(38,0),
  PRODUCT_CATEGORY VARCHAR(50),
  PRODUCT_NAME VARCHAR(200),
  CUSTOMER_SEGMENT VARCHAR(50),
  RATING NUMBER(38,0),
  REVIEW_TEXT VARCHAR(2000),
  STORE_LOCATION VARCHAR(50)
);
