-- TABLE: SUPPLY_CHAIN.FACT_INVENTORY_ALERTS

CREATE TABLE IF NOT EXISTS FACT_INVENTORY_ALERTS (
  ALERT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
  ALERT_DATE TIMESTAMP_NTZ(9),
  STORE_ID NUMBER(38,0),
  DEPARTMENT VARCHAR(50),
  PRODUCT_SKU VARCHAR(20),
  PRODUCT_NAME VARCHAR(200),
  ALERT_TYPE VARCHAR(30),
  ALERT_MESSAGE VARCHAR(1000),
  CURRENT_STOCK NUMBER(38,0),
  REORDER_POINT NUMBER(38,0),
  primary key (ALERT_ID)
);
