-- TABLE: RETAIL.FACT_DAILY_STORE_PERFORMANCE

CREATE TABLE IF NOT EXISTS FACT_DAILY_STORE_PERFORMANCE (
  PERFORMANCE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
  PERFORMANCE_DATE DATE,
  STORE_ID NUMBER(38,0),
  TOTAL_REVENUE NUMBER(12,2),
  TOTAL_TRANSACTIONS NUMBER(38,0),
  AVG_BASKET_SIZE NUMBER(10,2),
  FOOT_TRAFFIC NUMBER(38,0),
  CONVERSION_RATE NUMBER(5,2),
  GROSS_PROFIT NUMBER(12,2),
  SHRINKAGE_LOSS NUMBER(10,2),
  primary key (PERFORMANCE_ID)
);
