-- TABLE: SUPPLY_CHAIN.DIM_SUPPLIERS

CREATE TABLE IF NOT EXISTS DIM_SUPPLIERS (
  SUPPLIER_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
  SUPPLIER_CODE VARCHAR(20),
  SUPPLIER_NAME VARCHAR(200),
  COUNTRY VARCHAR(50),
  CATEGORY VARCHAR(50),
  CONTACT_EMAIL VARCHAR(200),
  LEAD_TIME_DAYS NUMBER(38,0),
  RELIABILITY_SCORE NUMBER(3,2),
  IS_CERTIFIED_ORGANIC BOOLEAN,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  primary key (SUPPLIER_ID)
);
