-- DCM Project: Sales Transactions table
-- Source: COLES_RETAIL_DB.RETAIL.FACT_SALES_TRANSACTIONS

DEFINE TABLE COLES_RETAIL_DB{{env_suffix}}.RETAIL.FACT_SALES_TRANSACTIONS (
  TXN_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  INV_DT DATE,
  INV_TM TIME(9),
  LOC_ID NUMBER(38,0),
  MERCH_ID NUMBER(38,0),
  SEG_CDE VARCHAR(50),
  UNIT_CNT NUMBER(38,0),
  BASE_PRC NUMBER(10,2),
  NET_AMT NUMBER(10,2),
  DISC_AMT NUMBER(10,2),
  MARGIN_AMT NUMBER(10,2),
  TENDER_CDE VARCHAR(20),
  FULFIL_CDE VARCHAR(5),
  PRIMARY KEY (TXN_ID)
);
